[tool.poetry]
name = "deepdict"
version = "1.2"
description = "DeepDict: Easy traversal of deeply nested dicts."
authors = ["Henrique Bastos <henrique@bastos.net>", "Matthew Scott <matt@11craft.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
